kind: Service
apiVersion: v1
metadata:
  name: netbox-mcp-server
  namespace: <enter_your_namespace_or_create_one>
spec:
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: netbox-mcp-server
