[project]
name = "netbox-mcp-server"
version = "0.1.0"
description = "A read-only MCP server for NetBox"
readme = "../README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.3.0",
    "requests>=2.31.0",
]
